language: java
jdk:
  - openjdk17


branches:
  only:
    - master


# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - "./gradlew clean build"

before_deploy:
  # AWS CodeDeploy는 jar 파일 인식 불가능 - Zip 파일로 압축
  # 현재 위치 (프로젝트) 모든 파일을 압축
  - zip -r Trip-to-Leave *
  # TravisCI가 실행중인 위치에서 dir 생성
  - mkdir -p deploy
  - mv Trip-to-Leave.zip deploy/Trip-to-Leave.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yuseonjun-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: yuseonjun-springboot-build
    key: Trip-to-Leave.zip
    bundle_type: zip
    application: yuseonjun-springboot2-webservice
    deployment_group: yuseonjun-springboot2-webservice-group

    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - seonjun0906@gmail.com