spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    spring:
      jpa:
        properties:
          hibernate:
            dialect:
              storage_engine=innodb:


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate:
        dialect: MySQL57Dialect
      jdbc:
        lob:
          non_contextual_creation: true
      hibernate.format_sql: true

  thymeleaf:
    cache: false

  profiles:
    include: oauth

  devtools:
    livereload:
      enabled: true

logging:
  level:
    root: debug
    com.study.trip: debug





